eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
#  cloud:
#    gateway:
#      routes:
#        - id: news-service
#          uri: lb://news-service
#          predicates:
#            - Path=/news/**
#        - id: comment-service
#          uri: lb://comment-service
#          predicates:
#            - Path=/comments/**
#        - id: api-news
#          uri: lb://api-news
#          predicates:
#            - Path=/api/**
debug: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: 8082
